# Generated by Django 4.1.2 on 2022-10-30 02:23

from django.db import migrations, models


def migrate_day_of_the_week(apps, schema_editor):
    """Create DayOfTheWeek records."""
    DayOfTheWeek = apps.get_model("app", "DayOfTheWeek")

    days_of_the_week = [
        "Segunda-feira",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado",
        "Domingo",
    ]
    for day in days_of_the_week:
        DayOfTheWeek.objects.create(description=day)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayOfTheWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Dia da Semana"
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_day_of_the_week),
    ]
