# Generated by Django 4.1.2 on 2022-10-30 05:10

import django.db.models.deletion
from django.db import migrations, models


def migrate_day_of_the_week(apps, schema_editor):
    """Create a CommissionParam for each DayOfTheWeek record."""
    DayOfTheWeek = apps.get_model("app", "DayOfTheWeek")
    CommissionParam = apps.get_model("app", "CommissionParam")

    for dotw in DayOfTheWeek.objects.all():
        CommissionParam.objects.create(day_of_the_week=dotw)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=3,
                        max_digits=5,
                        verbose_name="Percentual mínimo",
                    ),
                ),
                (
                    "max_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="Percentual máximo",
                    ),
                ),
                (
                    "day_of_the_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_param",
                        to="app.dayoftheweek",
                        verbose_name="Dia da semana",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_day_of_the_week),
    ]
