# Generated by Django 4.1.2 on 2022-10-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_commissionparam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionparam",
            name="day_of_the_week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_param",
                to="app.dayoftheweek",
                unique=True,
                verbose_name="Dia da semana",
            ),
        ),
    ]
