# Generated by Django 4.1.2 on 2022-10-31 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_commissionparam_day_of_the_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionparam",
            name="max_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Percentual máximo",
            ),
        ),
        migrations.AlterField(
            model_name="commissionparam",
            name="min_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Percentual mínimo",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionparam",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("min_percentage__gte", 0.0), ("min_percentage__lte", 10.0)
                ),
                name="app_commissionparam_min_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionparam",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("max_percentage__gte", 0.0), ("max_percentage__lte", 10.0)
                ),
                name="app_commissionparam_max_percentage_range",
            ),
        ),
    ]
