# Generated by Django 4.1.2 on 2022-10-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_commissionparam_max_percentage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commissionparam",
            options={
                "ordering": ("id",),
                "verbose_name": "Parâmetro de Comissão",
                "verbose_name_plural": "Parâmetros de Comissão",
            },
        ),
        migrations.AlterModelOptions(
            name="dayoftheweek",
            options={
                "ordering": ("id",),
                "verbose_name": "Dia da semana",
                "verbose_name_plural": "Dias da semana",
            },
        ),
    ]
