# Generated by Django 4.1.2 on 2022-11-02 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_product_product_app_product_min_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Percentual de comissão",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Valor unitário",
            ),
        ),
    ]
