# Generated by Django 4.1.2 on 2022-11-03 02:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_product_commission_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Venda",
                "verbose_name_plural": "Itens de Venda",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Data/hora")),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Número da nota fiscal"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="app.productitem", verbose_name="Itens de Venda"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.seller",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="productitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)),
                name="app_productitem_min_quantity",
            ),
        ),
    ]
