# Generated by Django 4.1.2 on 2022-11-07 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_productitem_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Venda",
                "verbose_name_plural": "Itens de Venda",
                "ordering": ("id",),
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.DeleteModel(
            name="ProductItem",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.order",
                verbose_name="Venda",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 1)), name="app_orderitem_min_quantity"
            ),
        ),
    ]
